### ISSUE TITLE
npm start does not work 

### ISSUE THREAD

**Issue by sagesaintsalem** [aucoeur/rpdrAPI#15]
Terminal error message - "sh: nodemon: command not found"

Also, there is no api folder in the repo. I cannot see the data anywhere.

**Comment by aucoeur** [comment]
ah sorry, just saw this.  the error was likely because `nodemon` wasn't installed globally and was also missing from the devDependencies.

as for the data, that is long lost now, but if you're still looking for data, there seems to be some extensive datasets available here: https://shiraamitchell.github.io/rpdr or here: https://cran.r-project.org/web/packages/dragracer/readme/README.html
